In [1]:
import numpy as np
import numpy

mean1 = [0, 0]
cov1 = [[1, 0.5], [0.5, 1]]  

mean2 = [2, 2]
cov2 = [[1, 0.4], [0.4, 1]]  

mean3 = [4, 1]
cov3 = [[1, 0.3], [0.3, 1]] 

train = []
test = []

for i in range(50):
    train.append(np.random.multivariate_normal(mean1,cov1))
for i in range(50):
    train.append(np.random.multivariate_normal(mean2,cov2))
for i in range(50):
    train.append(numpy.random.multivariate_normal(mean3,cov3))

for i in range(50):
    test.append(numpy.random.multivariate_normal(mean1,cov1))
for i in range(50):
    test.append(numpy.random.multivariate_normal(mean2,cov2))
for i in range(50):
    test.append(numpy.random.multivariate_normal(mean3,cov3))

# print(train)
# print(test)



In [2]:
bin_nums = 6

In [3]:
def get_indice(val,edges):
    if val < edges[0]:
        return -1
    for i in range(len(edges)-1):
        if val >= edges[i] and val <= edges[i+1]:
            return i
    return -1

In [4]:
H1,x1,y1 = numpy.histogram2d([t[0] for t in train[:50]],[t[1] for t in train[:50]],bins=bin_nums)
H2,x2,y2 = numpy.histogram2d([t[0] for t in train[50:100]],[t[1] for t in train[50:100]],bins=bin_nums)
H3,x3,y3 = numpy.histogram2d([t[0] for t in train[100:]],[t[1] for t in train[100:]],bins=bin_nums)

Hs = [H1,H2,H3]
xs = [x1,x2,x3]
ys = [y1,y2,y3]
# print(H1)


In [5]:
def get_label(test_record):
    max_score = -1
    max_label = 0
    for j in range(3):
        idx1 = get_indice(test_record[0],xs[j])
        idx2 = get_indice(test_record[1],ys[j])
        if idx1==-1 or idx2==-1:
            score = 0
        else:    
            score = (Hs[j])[idx2][idx1]
        if score >= max_score:
#             print(score)
            max_score = score
            max_label = j+1
    if max_label == 0:
        max_label = np.random.randint(1,4)
    return max_label

In [6]:

confmat = np.zeros((3,3))
correctly = 0
for i in range(50):
    l = get_label(test[i])
    confmat[l-1][0] +=1
    if l == 1:
        correctly+=1
        
# print('---------')
for i in range(50,100):
    l = get_label(test[i])
    confmat[l-1][1] +=1
#     print(max_label)
    if l == 2:
        correctly+=1
# print('------------------')
for i in range(100,150):
    l = get_label(test[i])
    confmat[l-1][2] +=1
    if l == 3:
        correctly+=1
print("test accuracy",correctly/150)

test accuracy 0.72


In [8]:
print("test confusion matrix\n",confmat)


test confusion matrix
 [[31. 14.  0.]
 [ 9. 30.  3.]
 [10.  6. 47.]]


In [9]:

train_confmat = np.zeros((3,3))
correctly = 0
for i in range(50):
    l = get_label(train[i])
    train_confmat[l-1][0] +=1
    if l == 1:
        correctly+=1
        
# print('---------')
for i in range(50,100):
    l = get_label(train[i])
    train_confmat[l-1][1] +=1
#     print(max_label)
    if l == 2:
        correctly+=1
# print('------------------')
for i in range(100,150):
    l = get_label(train[i])
    train_confmat[l-1][2] +=1
    if l == 3:
        correctly+=1
print("train accuracy",correctly/150)
print("train confusion matrix\n",train_confmat)

train accuracy 0.78
train confusion matrix
 [[33.  6.  1.]
 [10. 38.  3.]
 [ 7.  6. 46.]]
